import { ProductProps } from "@/props/product";

export const localProducts: ProductProps[] = [
  {
    id: 5,
    name: "Bot Chat YouTube",
    description: "Bot untuk mengirim komentar otomatis ke live stream YouTube.",
    image: "/images/products/youtube-logo.svg",
    category: "CLI apps",
    features: [
      "Kirim komentar otomatis ke live stream YouTube",
      "Konfigurasi mudah via file config",
      "Mendukung multiple akun",
      "Jadwalkan komentar secara otomatis",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Go"],
    docs: "https://github.com/jhonoryza/bot-chat-youtube",
    policy_url: null,
  },
  {
    id: 6,
    name: "Config Opener",
    description:
      "Aplikasi desktop ringan berbasis C murni dan GTK3 untuk macOS yang menampilkan daftar file konfigurasi dan membukanya dengan Sublime Text.",
    image: "/images/products/tools-logo.svg",
    category: "Desktop apps",
    features: [
      "Tampilkan daftar file konfigurasi",
      "Buka file dengan Sublime Text",
      "Antarmuka GTK3 yang ringan",
      "Dibangun dengan C murni",
      "Khusus macOS",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["C", "GTK3"],
    docs: "https://github.com/jhonoryza/c-gtk3-opentool-desktop",
    policy_url: null,
  },
  {
    id: 7,
    name: "Sublime Supermaven Plugin",
    description: "Supermaven plugin for Sublime Text — AI code completion langsung di editor favorit Anda.",
    image: "/images/products/sublime-logo.svg",
    category: "IDE Plugin",
    features: [
      "AI code completion powered by Supermaven",
      "Integrasi mulus dengan Sublime Text",
      "Respons cepat dan akurat",
      "Mudah diinstal dan dikonfigurasi",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Python"],
    docs: "https://github.com/jhonoryza/sublime-supermaven-plugin",
    policy_url: null,
  },
  {
    id: 8,
    name: "Open API",
    description: "Dokumentasi REST API publik Labkita — referensi endpoint, schema, dan contoh request/response.",
    image: "/images/products/api-logo.svg",
    category: "API",
    features: [
      "Dokumentasi interaktif berbasis OpenAPI / Swagger",
      "Coba endpoint langsung dari browser",
      "Skema request & response lengkap",
      "Autentikasi API key",
      "Selalu up-to-date dengan versi terbaru",
    ],
    is_opensource: false,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["REST", "OpenAPI"],
    docs: "https://api-blog.labkita.my.id/doc",
    policy_url: null,
  },
  {
    id: 9,
    name: "Docker Linux",
    description: "Jalankan distribusi Linux di dalam container Docker — ringan, cepat, dan terisolasi.",
    image: "/images/products/tools-logo.svg",
    category: "Docker",
    features: [
      "Berbagai distro Linux dalam satu container",
      "Ringan dan cepat tanpa VM",
      "Isolasi lingkungan yang aman",
      "Mudah dikonfigurasi dan di-deploy",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Docker", "Linux"],
    docs: "https://github.com/jhonoryza/docker-linux",
    policy_url: null,
  },
  {
    id: 10,
    name: "Docker Windows",
    description: "Jalankan Windows di dalam container Docker — solusi ringan untuk pengujian dan development.",
    image: "/images/products/tools-logo.svg",
    category: "Docker",
    features: [
      "Windows environment dalam container Docker",
      "Cocok untuk CI/CD dan pengujian",
      "Konfigurasi fleksibel",
      "Ringan dibandingkan VM tradisional",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Docker", "Windows"],
    docs: "https://github.com/jhonoryza/docker-windows",
    policy_url: null,
  },
  {
    id: 11,
    name: "Docker Android",
    description: "Jalankan Android di dalam container Docker — emulasi Android ringan untuk pengembangan aplikasi.",
    image: "/images/products/tools-logo.svg",
    category: "Docker",
    features: [
      "Android environment dalam container Docker",
      "Cocok untuk automated testing",
      "Ringan dan mudah di-deploy",
      "Mendukung berbagai versi Android",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Docker", "Android"],
    docs: "https://github.com/jhonoryza/docker-android-fork",
    policy_url: null,
  },
  {
    id: 12,
    name: "Omarchy",
    description: "Arch Linux yang ramping dan minimalis — tanpa bloatware, siap pakai di container dan server.",
    image: "/images/products/tools-logo.svg",
    category: "Linux",
    features: [
      "Arch Linux minimal tanpa bloatware",
      "Dioptimalkan untuk container dan server",
      "Ringan dan cepat",
      "Mudah dikustomisasi",
    ],
    is_opensource: true,
    pricing: [{ plan: "Free", price: "free" }],
    techStack: ["Linux", "Arch Linux", "Bash"],
    docs: "https://github.com/jhonoryza/omarchy-fork",
    policy_url: null,
  },
];
